version: '3'
networks:
    laravel:

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        working_dir:
            /var/www
        depends_on:
            - php
            - db
        networks:
            - laravel
    php:
        build: ./docker/php
        container_name: php
        volumes:
            - ./src:/var/www
        working_dir:
            /var/www
        networks:
            - laravel
    db:
        image: mysql:5.7
        ports:
            - "3360:3360"
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: time3483
        networks:
            - laravel
volumes:
    data: